services:
- type: web
  name: papernexus-api
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn api:app
  envVars:
    - key: PYTHON_VERSION
      value: 3.9.0

- type: web
  name: papernexus-ui
  buildCommand: cd papernexus-ui && npm install && npm run build
  staticPublishPath: ./papernexus-ui/dist # Or your build output folder